    const imagegeneratordata = [
    {
        id: 1,
        proimg: "assets/images/avatar/03.png",
        title: "what is openup?",
        Openupimg: "assets/images/avatar/04.png",
        Openup:"Openup",
        des:"The Open Unified Process, is a simplified version of the Rational Unified Process (RUP) used for agile and iterative software development. It was developed within the Eclipse Foundation and is based on the donation of process content by IBM.",
        img1: "assets/images/generator/04.jpg",
        img2:"assets/images/generator/05.jpg",
        figure:"“A whimsical, bold, and colorful humanoid figure”",   
    },  
    {
        id: 2,
        proimg: "assets/images/avatar/03.png",
        title: "what is openup?",
        Openupimg: "assets/images/avatar/04.png",
        Openup:"Openup",
        des:"The Open Unified Process, is a simplified version of the Rational Unified Process (RUP) used for agile and iterative software development. It was developed within the Eclipse Foundation and is based on the donation of process content by IBM. OpenUP targets small and colocated teams interested in agile and iterative development and is a lean Unified Process that applies iterative and incremental approaches within a structured lifecycle. It embraces a pragmatic approach and is positioned as an easy and flexible version of RUP [1][2][3]",
        img1: "assets/images/generator/06.jpg",
        img2:"assets/images/generator/07.jpg",
        figure:"“A whimsical, bold, and colorful humanoid figure”",
    },
    {
        id: 3,
        proimg: "assets/images/avatar/03.png",
        title: "what is openup?",
        Openupimg: "assets/images/avatar/04.png",
        Openup:"Openup",
        des:"Working with a chatbot involves several steps, from designing and building the bot to deploying and maintaining it. Here's a general overview of how to work with a chatbot:",
        img1: "assets/images/generator/04.jpg",
        img2:"assets/images/generator/05.jpg",
        figure:"“A whimsical, bold, and colorful humanoid figure”",
    },
]
export { imagegeneratordata };